### ISSUE TITLE
[CHORE] 프로젝트 기초셋팅

### ISSUE THREAD

**Issue by mdb1217** [TeamLOG-INU/FIVE-ANDROID#1]
## 💡 Issue
프로젝트 초기 세팅 완료하기!

## 📝 todo
- [x] 라이브러리 추가
- [x] BaseActivity, Fragment 추가
- [x] PR, ISSUE 템플릿
- [x] 위키 작성
> - [x] 커밋 룰
> - [x] 코드 컨벤션
- [x] 서버 기초 세팅 + enqueue 유틸
